version: '3.9'
services:
  frontend:
    build: ../../frontend
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000
    depends_on:
      - backend
  backend:
    build: ../../backend
    ports:
      - '4000:4000'
    environment:
      NODE_ENV: development
      POSTGRES_URL: postgres://postgres:postgres@postgres:5432/brainy
      REDIS_URL: redis://redis:6379
      JWT_SECRET: super-secret
      GOOGLE_SPEECH_API_KEY: change-me
      OPENAI_API_KEY: change-me
      CHATTERBOX_URL: http://chatterbox:8080
    depends_on:
      - postgres
      - redis
      - chatterbox
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: brainy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - '6379:6379'
  chatterbox:
    image: ghcr.io/acme/chatterbox-self-hosted:latest
    environment:
      MODEL_PATH: /models
    volumes:
      - chatterbox-models:/models
    ports:
      - '8080:8080'
volumes:
  postgres-data:
  chatterbox-models:
