apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainy-frontend
  labels:
    app: brainy-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: brainy-frontend
  template:
    metadata:
      labels:
        app: brainy-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/acme/brainy-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.brainy.ai"
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: brainy-frontend
spec:
  selector:
    app: brainy-frontend
  ports:
    - port: 80
      targetPort: 3000
      name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: brainy-frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: brainy-frontend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
