apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: brainy-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: brainy-postgres
spec:
  selector:
    matchLabels:
      app: brainy-postgres
  serviceName: brainy-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: brainy-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: brainy
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: brainy-secrets
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
---
apiVersion: v1
kind: Service
metadata:
  name: brainy-postgres
spec:
  selector:
    app: brainy-postgres
  ports:
    - port: 5432
      targetPort: 5432
