apiVersion: apps/v1
kind: Deployment
metadata:
  name: brainy-redis
  labels:
    app: brainy-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: brainy-redis
  template:
    metadata:
      labels:
        app: brainy-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: brainy-redis
spec:
  selector:
    app: brainy-redis
  ports:
    - port: 6379
      targetPort: 6379
